-- MySQL Script generated by MySQL Workbench
-- Mon May  9 16:38:04 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema AttendanceTracker3nf
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema AttendanceTracker3nf
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AttendanceTracker3nf` DEFAULT CHARACTER SET utf8 ;
USE `AttendanceTracker3nf` ;

-- -----------------------------------------------------
-- Table `AttendanceTracker3nf`.`employees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AttendanceTracker3nf`.`employees` ;

CREATE TABLE IF NOT EXISTS `AttendanceTracker3nf`.`employees` (
  `Employee_ID` INT(10) NOT NULL AUTO_INCREMENT,
  `Birth_Date` DATETIME NULL DEFAULT NULL,
  `fname` VARCHAR(255) NULL DEFAULT NULL,
  `lname` VARCHAR(255) NULL DEFAULT NULL,
  `Gender` ENUM('M', 'F') NULL DEFAULT NULL,
  `Hire_Date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`Employee_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `AttendanceTracker3nf`.`Personal_Days_Off`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AttendanceTracker3nf`.`Personal_Days_Off` ;

CREATE TABLE IF NOT EXISTS `AttendanceTracker3nf`.`Personal_Days_Off` (
  `personaldayID` INT(11) NOT NULL,
  `Personal_Reason` VARCHAR(45) NULL DEFAULT NULL,
  `Personal_Date` DATETIME NULL DEFAULT NULL,
  `Personal_Status` VARCHAR(45) NULL DEFAULT NULL,
  `Personal_Days_Offcol` VARCHAR(45) NULL,
  `fk_Employee_ID_Personal_Days_Off` INT NULL,
  PRIMARY KEY (`personaldayID`),
  INDEX `Employee_ID_idx` (`fk_Employee_ID_Personal_Days_Off` ASC),
  CONSTRAINT `Employee_ID`
    FOREIGN KEY (`fk_Employee_ID_Personal_Days_Off`)
    REFERENCES `AttendanceTracker3nf`.`employees` (`Employee_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `AttendanceTracker3nf`.`Sick_Days_Off`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AttendanceTracker3nf`.`Sick_Days_Off` ;

CREATE TABLE IF NOT EXISTS `AttendanceTracker3nf`.`Sick_Days_Off` (
  `sickdayID` INT(11) NOT NULL,
  `Sick_Date` DATETIME NULL DEFAULT NULL,
  `fk_Employee_ID_Sick_Days_Off` INT NULL,
  PRIMARY KEY (`sickdayID`),
  INDEX `Employee_ID_idx` (`fk_Employee_ID_Sick_Days_Off` ASC),
  CONSTRAINT `fk_Employee_ID_Sick_Days_Off`
    FOREIGN KEY (`fk_Employee_ID_Sick_Days_Off`)
    REFERENCES `AttendanceTracker3nf`.`employees` (`Employee_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `AttendanceTracker3nf`.`Vaction_Time`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AttendanceTracker3nf`.`Vaction_Time` ;

CREATE TABLE IF NOT EXISTS `AttendanceTracker3nf`.`Vaction_Time` (
  `vactionID` INT(11) NOT NULL,
  `Vaction_From_Date` DATETIME NOT NULL,
  `Vaction_To_Date` DATETIME NOT NULL,
  `Vaction_Time_Status` VARCHAR(45) NULL DEFAULT NULL,
  `fk_Employee_ID_VactionTime` INT NULL,
  PRIMARY KEY (`vactionID`),
  INDEX `Employee_ID_idx` (`fk_Employee_ID_VactionTime` ASC),
  CONSTRAINT `fk_Employee_ID_VactionTime`
    FOREIGN KEY (`fk_Employee_ID_VactionTime`)
    REFERENCES `AttendanceTracker3nf`.`employees` (`Employee_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `AttendanceTracker3nf`.`login`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AttendanceTracker3nf`.`login` ;

CREATE TABLE IF NOT EXISTS `AttendanceTracker3nf`.`login` (
  `LoginID` INT(10) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(32) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `roles` ENUM('Employee', 'Manager', 'Human Resources', 'Admin') NULL DEFAULT NULL,
  `allowedvacationdays` INT(11) NULL DEFAULT '15',
  `allowedsickdays` INT(11) NULL DEFAULT '7',
  `employees_Employee_ID` INT(10) NOT NULL,
  PRIMARY KEY (`LoginID`),
  INDEX `fk_login_employees1_idx` (`employees_Employee_ID` ASC),
  CONSTRAINT `fk_login_employees1`
    FOREIGN KEY (`employees_Employee_ID`)
    REFERENCES `AttendanceTracker3nf`.`employees` (`Employee_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
